/**
 * 원장용 요약 화면(DoctorView) 미리보기용 예시 데이터.
 *
 * 절대 payload JSON을 손으로 쓰지 않는다 — 실제 App.tsx `phase === 'done'`과
 * 동일한 builder(buildResponsePayload/buildRoutingPayload/computeFlags/
 * computeSaju+buildSajuInput)를 손으로 만든 응답(Responses) 위에 그대로
 * 실행해서 payload를 만든다. 그래야 스펙이 바뀌면 fixture도 자동으로 같이
 * 깨지거나 같이 맞아 떨어진다(드리프트 불가능).
 */
import {
  ALL_QUESTIONS,
  buildResponsePayload,
  buildRoutingPayload,
  buildSajuInput,
  computeFlags,
  pruneStaleResponses,
} from '../spec/coreSpec'
import { computeSaju } from '../saju'
import type { Responses } from '../types'
import type { DoctorFixture, DoctorPayload } from './types'

const emptyResponses = (): Responses =>
  Object.fromEntries(ALL_QUESTIONS.map((q) => [q.id, null]))

/** 대부분의 fixture가 공유하는, 문진 시나리오와 무관한 최소 공통 응답. */
const BASE_DEFAULTS: Responses = {
  ID_02: '1234',
  MED_USE: 'none',
  HISTORY_01: ['none'],
  ALLERGY_01: 'none',
  SURGERY_01: 'none',
  TEST_01: 'none',
  FREE_01: 'none',
  HERB_APPETITE: 'normal',
  HERB_THERMAL: 'cold_sensitive',
  HERB_THIRST: 'normal',
  HERB_SWEAT: 'normal',
  BIRTH_02: 'solar',
  BIRTH_03: 'o',
  BIRTH_03A: 'exact',
}

let seq = 0

function buildFixture(name: string, patch: Responses): DoctorFixture {
  seq += 1
  const merged: Responses = { ...emptyResponses(), ...BASE_DEFAULTS, ...patch }
  const { responses } = pruneStaleResponses(merged)

  const payload: DoctorPayload = {
    questionnaire_version: '1.0',
    session_id: `fixture-${seq}`,
    responses: buildResponsePayload(responses),
    flags: computeFlags(responses),
    routing: buildRoutingPayload(responses),
    myungri_calculation: computeSaju(buildSajuInput(responses)),
    metadata: { session_started_at: null, answers: {} },
  }

  return { name, payload }
}

export const DOCTOR_FIXTURES: DoctorFixture[] = [
  buildFixture('수면 주호소 + 동반 소화/통증', {
    ID_01: '김민준',
    ID_03: 'male',
    BIRTH_01: '19850312',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'sleep',
    VISIT_03_SYMPTOM_DURATION: '1_3m',
    VISIT_04_SYMPTOM_IMPACT: 'moderate',
    SECONDARY_01: ['digestion', 'pain'],
    SAFETY_01: ['none'],
    SLEEP_01: ['sleep_onset', 'night_awakenings'],
    SLEEP_02: '3_4_days',
    SLEEP_03: ['racing_thoughts'],
    SEC_GI_01: ['indigestion', 'reflux'],
    SEC_PAIN_01: ['neck_shoulder'],
    MED_USE: 'yes',
    MED_TYPES: ['psych'],
  }),

  // 음력 + 윤달 케이스 (1995년 윤8월 15일은 manseryeok에서 실제로 변환 가능함).
  buildFixture('여성 건강 주호소', {
    ID_01: '이서연',
    ID_03: 'female',
    BIRTH_01: '19950815',
    BIRTH_02: 'lunar',
    BIRTH_02A: 'yes',
    VISIT_01: 'women',
    VISIT_02_WOMEN: 'women',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    WOMEN_01: ['irregular_cycle', 'menopause_symptoms'],
    WOMEN_02: 'irregular_current',
    WOMEN_03: ['hot_flash', 'sweating'],
    WOMEN_SAFETY_01: ['menopause'],
  }),

  buildFixture('임신 상담', {
    ID_01: '박지현',
    ID_03: 'female',
    BIRTH_01: '19960120',
    VISIT_01: 'women',
    VISIT_02_WOMEN: 'pregnancy',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PREGNANCY_01: 'pregnant',
    PREGNANCY_02: 'second_trimester',
    PREGNANCY_03: ['nausea', 'fatigue'],
  }),

  buildFixture('산후 회복', {
    ID_01: '최유진',
    ID_03: 'female',
    BIRTH_01: '19910815',
    VISIT_01: 'women',
    VISIT_02_WOMEN: 'postpartum',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    POSTPARTUM_01: '6w_to_3m',
    POSTPARTUM_02: ['fatigue_recovery', 'sleep_fatigue'],
    POSTPARTUM_03: 'yes',
  }),

  // 출생시간 모름(time-unknown) 케이스 -> myungri_calculation.status === 'partial'
  buildFixture('체중 관리', {
    ID_01: '정도윤',
    ID_03: 'male',
    BIRTH_01: '19880703',
    BIRTH_03: 'unknown',
    VISIT_01: 'weight',
    SECONDARY_01: ['sleep'],
    SAFETY_01: ['none'],
    SEC_SLEEP_01: ['nonrestorative'],
    WEIGHT_01: 'weight_loss',
    WEIGHT_02: ['snacking_night_eating', 'stress_eating'],
    WEIGHT_03: 'gaining',
    WEIGHT_04: 'lifestyle',
  }),

  buildFixture('체질·보약', {
    ID_01: '한지호',
    ID_03: 'male',
    BIRTH_01: '19790910',
    VISIT_01: 'constitution',
    VISIT_02_CONST: 'constitution',
    SECONDARY_01: ['fatigue'],
    SAFETY_01: ['none'],
    SEC_FATIGUE_01: ['morning_fatigue'],
    CONST_ENERGY: 'tired_recovers',
    CONST_SLEEP: 'frequent_waking',
    CONST_DIGESTION: 'occasional',
    CONST_BOWEL: 'regular',
  }),

  // MENOPAUSE_SLEEP v0.2 Compact: Gate=yes + maintenance/early_waking 최악
  // branch + 우선 확인 필요 sleep disorder flag 동시 발생 케이스.
  buildFixture('여성 수면 주호소 + 갱년기 연동', {
    ID_01: '강수정',
    ID_03: 'female',
    BIRTH_01: '19740612',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'sleep',
    VISIT_03_SYMPTOM_DURATION: '1_3m',
    VISIT_04_SYMPTOM_IMPACT: 'moderate',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    SLEEP_01: ['night_awakenings', 'early_waking'],
    SLEEP_02: '5_plus_days',
    SLEEP_03: ['heat_sweat'],
    MS_GATE_01: 'yes',
    MS_01: 'cycle_changing',
    MS_02: 'several_week',
    MS_03: 'frequent',
    MS_04: '5_6h',
    MS_05: ['witnessed_apnea'],
    MS_06: 'two_three',
    MS_07: '30_60m',
    WOMEN_SAFETY_01: ['none'],
  }),

  // SAFETY_01 red flag + BOWEL_03='yes' 동시 발생 -> requires_staff_check true.
  // 자시(23:00~00:59) 출생 -> policy.pending_approval에 day_boundary 포함.
  buildFixture('안전 확인 필요', {
    ID_01: '오세훈',
    ID_03: 'male',
    BIRTH_01: '19750501',
    BIRTH_03: 'ja',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'bowel',
    VISIT_03_SYMPTOM_DURATION: 'over_1y',
    VISIT_04_SYMPTOM_IMPACT: 'severe',
    SECONDARY_01: ['none'],
    SAFETY_01: ['sudden_severe_pain'],
    BOWEL_01: ['constipation', 'abdominal_discomfort'],
    BOWEL_02: 'less_than_3_per_week',
    BOWEL_03: 'yes',
    BOWEL_04: 'often',
  }),

  // LBP_V1: 양쪽 다리 + 구체적 신경 증상(NUMBNESS) -> lbp_safety_status
  // REVIEW_REQUIRED (결정 §2, checklist item 5). primary_module은 'Pain'
  // 그대로, primary_module_detail만 'LBP' — 이전까지 primary-pain fixture가
  // 하나도 없었다(Opus review S9).
  buildFixture('허리 통증 주호소 (LBP, 확인 필요)', {
    ID_01: '조현우',
    ID_03: 'male',
    BIRTH_01: '19700615',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: '3m_1y',
    VISIT_04_SYMPTOM_IMPACT: 'moderate',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'low_back_pelvis',
    PAIN_02: ['aching', 'movement_related'],
    PAIN_04: 'lower_limb',
    LBP_01: 'BUTTOCK',
    LBP_02: ['NUMBNESS'],
    LBP_03: 'BILATERAL',
    LBP_04: ['NONE'],
    LBP_05: ['NONE'],
    LBP_06: 'NO',
    LBP_07: 'YES',
    LBP_08: 'NO',
    LBP_10: 'NO',
    LBP_11: ['NONE'],
    LBP_12: 6,
    LBP_13: 'SOMEWHAT',
    LBP_14: 'SOME',
  }),

  // NECK_V1: N02(HAND_CLUMSINESS, non-urgent concrete positive) + N02A
  // STABLE -> neck_safety_status REVIEW_REQUIRED (not urgent). N07=
  // HAND_FINGERS + N09 concrete neuro(PARESTHESIA) -> radicular_support
  // HIGHER_SUPPORT. N10=YES/N10A=NO/N11=YES -> headache present but not
  // new/changed, cervicogenic pattern considered. primary_module stays
  // 'Pain', primary_module_detail becomes 'NECK' (v0.2.1 §9, mirrors the
  // LBP fixture's primary_module_detail pattern above).
  buildFixture('목 통증 주호소 (NECK, 확인 필요)', {
    ID_01: '박서준',
    ID_03: 'male',
    BIRTH_01: '19800101',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: '3m_1y',
    VISIT_04_SYMPTOM_IMPACT: 'moderate',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'neck_shoulder',
    PAIN_02: ['aching', 'movement_related'],
    PAIN_04: 'upper_limb',
    NECK_01: 'NO',
    NECK_02: ['HAND_CLUMSINESS'],
    NECK_02A: 'STABLE',
    NECK_03A: 'NO',
    NECK_03B: 'NO',
    NECK_04: ['NONE'],
    NECK_05: ['NONE'],
    NECK_06: 'RIGHT',
    NECK_07: 'HAND_FINGERS',
    NECK_08: 'RIGHT',
    NECK_09: ['PARESTHESIA'],
    NECK_10: 'YES',
    NECK_10A: 'NO',
    NECK_11: 'YES',
    NECK_12: 'YES',
    // SHOULDER_V1 통합 후 추가: 이 fixture는 이미 존재했으므로 NS01/SH01/
    // SH04/SH05가 원래 없었다 -- 전부 valid-negative로 채워 이 환자가
    // 실제로는 답했을 값을 반영한다(F1: IS_PRIMARY_NECK 하나로 SH0x도
    // 게이트되므로, 채우지 않으면 fail-closed 때문에 shoulder_safety_status가
    // REVIEW_REQUIRED가 되어 이 NECK 전용 fixture의 의도(안전은 목
    // 문제로만 REVIEW)가 흐려진다). NECK_* 필드는 전혀 건드리지 않았다.
    NS01: 'NECK_DOMINANT',
    SH01: 'NO',
    SH04: 'NO',
    SH05: 'NO',
  }),

  // SHOULDER_V1: NS01=SHOULDER_DOMINANT -> primary_module_detail 'SHOULDER'.
  // SH01=YES(외상) + SH02=[NONE](변형/신경혈관 없음) + SH03=YES(외상 직후
  // 현저한 팔 들기 저하) -> shoulder_safety_status REVIEW_REQUIRED(URGENT
  // 아님, F3/결정 §11) + expedited_referral_consider=true. Canonical NECK는
  // 전부 valid-negative로 CLEAR -- 이 fixture가 "어깨 문제로만 REVIEW"임을
  // 분명히 한다(F1 대조군: NECK_DOMINANT 시나리오는 위 fixture가 반대로
  // "목 문제로만 REVIEW"를 보여준다).
  buildFixture('어깨 통증 주호소 (SHOULDER, 신속 의뢰 고려)', {
    ID_01: '이도현',
    ID_03: 'male',
    BIRTH_01: '19850615',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'severe',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'neck_shoulder',
    PAIN_02: ['sharp', 'movement_related'],
    PAIN_04: 'none',
    NS01: 'SHOULDER_DOMINANT',
    NECK_01: 'NO',
    NECK_02: ['NONE'],
    NECK_03A: 'NO',
    NECK_03B: 'NO',
    NECK_04: ['NONE'],
    NECK_05: ['NONE'],
    NECK_10: 'NO',
    SH01: 'YES',
    SH02: ['NONE'],
    SH03: 'YES',
    SH04: 'NO',
    SH05: 'NO',
    SH06: 'NO',
    SH07: 'RIGHT',
    SH08: 'YES',
    SH09: 'NO',
  }),

  // KNEE_V1: demonstrates both closed decisions in one fixture --
  // (1) K5 DVT de-escalation: KNEE_06=YES (leg swelling reported) +
  //     KNEE_06A=[NONE] (no concrete DVT risk factor) must NOT by itself
  //     create REVIEW_REQUIRED/dvt_assessment_required (Amendment A1's
  //     critical negative regression).
  // (2) K9 occult hip-fracture referred option: KNEE_08's new
  //     NEW_HIP_GROIN_PAIN_OR_WEIGHT_BEARING_DIFFICULTY_NOT_EXPLAINED_BY_KNEE
  //     is the sole positive safety finding here -> REVIEW_REQUIRED +
  //     fracture_imaging_consider (reusing the existing flag, no new tier).
  buildFixture('무릎 통증 주호소 (KNEE, 고관절 연관통 의심)', {
    ID_01: '최지훈',
    ID_03: 'male',
    BIRTH_01: '19600101',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: '1_3m',
    VISIT_04_SYMPTOM_IMPACT: 'moderate',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'knee',
    PAIN_02: ['aching', 'movement_related'],
    PAIN_04: 'none',
    KNEE_01: 'NO',
    KNEE_02: ['NONE'],
    KNEE_02A: 'NO',
    KNEE_05: 'NO',
    KNEE_06: 'YES',
    KNEE_06A: ['NONE'],
    KNEE_06B: ['NONE'],
    KNEE_07: 'NO',
    KNEE_08: ['NEW_HIP_GROIN_PAIN_OR_WEIGHT_BEARING_DIFFICULTY_NOT_EXPLAINED_BY_KNEE'],
    KNEE_09: 'RIGHT',
    KNEE_10: 'ANTERIOR',
    KNEE_11: ['STAIRS'],
    KNEE_12: 'UP_TO_30_MIN',
    KNEE_13: 'NO',
    KNEE_14: 'NO',
  }),

  // ELBOW_V1: demonstrates both closed decisions in one fixture --
  // (1) a genuine positive tier: ELBOW_04=YES (distal biceps concern after
  //     trauma) -> REVIEW_REQUIRED + expedited_referral_consider.
  // (2) E5 stable sensory-only de-escalation: ELBOW_09=YES (sensory
  //     symptoms present) + ELBOW_09A=[NONE] (explicitly no progressive
  //     weakness/wasting) must NOT independently add REVIEW_REQUIRED or
  //     neuro_assessment_required -- the only safety contribution in this
  //     fixture comes from ELBOW_04, proving the sensory-only path stays
  //     silent (Opus v0.1/v0.2/final verification's critical negative
  //     regression).
  buildFixture('팔꿈치 통증 주호소 (ELBOW, 신속 의뢰 고려)', {
    ID_01: '한도윤',
    ID_03: 'male',
    BIRTH_01: '19900101',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'severe',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'arm_hand',
    PAIN_02: ['sharp', 'movement_related'],
    PAIN_04: 'none',
    ELBOW_00: 'ELBOW',
    ELBOW_01: 'YES',
    ELBOW_02: ['NONE'],
    ELBOW_02A: 'NO',
    ELBOW_03: 'NO',
    ELBOW_04: 'YES',
    ELBOW_05: 'NO',
    ELBOW_06: 'NO',
    ELBOW_07: 'NO',
    ELBOW_08: 'NONE',
    ELBOW_09: 'YES',
    ELBOW_09A: ['NONE'],
    ELBOW_10: ['NONE'],
    ELBOW_11: ['NONE'],
    ELBOW_12: 'ANTERIOR',
    ELBOW_13: 'RIGHT',
    ELBOW_14: ['GRIPPING'],
    ELBOW_15: 'NO',
  }),
  buildFixture('손목 통증 주호소 (WRIST_HAND, 안정형 감각이상)', {
    ID_01: '서지우',
    ID_03: 'female',
    BIRTH_01: '19880615',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'moderate',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'arm_hand',
    PAIN_02: ['aching', 'numbness'],
    PAIN_04: 'none',
    ELBOW_00: 'WRIST_HAND',
    WH_01: 'NO',
    WH_02: ['NONE'],
    WH_06: ['NONE'],
    WH_07: 'NONE',
    // E5-류 CRITICAL fixture: 감각양성 + WH_08A=[NONE] -- stable sensory-only
    // de-escalation을 doctor.spec.mjs 2h 섹션에서 end-to-end로 검증한다.
    WH_08: 'MEDIAN_DISTRIBUTION',
    WH_08A: ['NONE'],
    WH_09: 'RADIAL_WRIST_THUMB_SIDE',
    WH_14: 'RIGHT',
  }),
  buildFixture('전완 통증 주호소 (FOREARM, 팔꿈치+손목 동시 노출)', {
    ID_01: '박하윤',
    ID_03: 'male',
    BIRTH_01: '19950320',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'severe',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'arm_hand',
    PAIN_02: ['sharp'],
    PAIN_04: 'none',
    // FOREARM: 이 저장소 최초로 ELBOW/WRIST_HAND protected safety가 동시에
    // 노출되는 케이스 -- ElbowSafetyPanel과 WristHandSafetyPanel이 둘 다
    // 렌더되어야 한다(doctor.spec.mjs 2h 섹션에서 검증).
    ELBOW_00: 'FOREARM',
    ELBOW_01: 'NO',
    ELBOW_02: ['NONE'],
    ELBOW_02A: 'NO',
    ELBOW_06: 'NO',
    ELBOW_07: 'NO',
    ELBOW_08: 'NONE',
    ELBOW_09: 'NO',
    ELBOW_10: ['NONE'],
    ELBOW_11: ['NONE'],
    WH_01: 'YES',
    WH_02: ['NONE'],
    WH_03: 'NO',
    WH_04: 'YES',
    WH_04A: 'DONE_TOLD_NORMAL',
    WH_05: 'NO',
    WH_06: ['NONE'],
    WH_07: 'NONE',
    WH_08: 'NONE',
  }),
  // ------------------------------------------------------------------
  // TMJ_V1 fixtures. PAIN_01: 'head_face_jaw' population, HFJ_00 shared
  // routing discriminator (T1). Each fixture below maps to one scenario
  // from the TMJ_V1 CLOSED Tablet Question Set v0.1 (T1-T8).
  // ------------------------------------------------------------------
  buildFixture('턱관절 통증 주호소 (TMJ, 안전 확인 완료)', {
    ID_01: '턱안전예시',
    ID_03: 'female',
    BIRTH_01: '19900101',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'mild',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'head_face_jaw',
    PAIN_02: ['aching', 'movement_related'],
    PAIN_04: 'none',
    // 1. clear mechanical TMJ -- protected safety 전부 명시적 negative.
    HFJ_00: 'JAW_TMJ_MASTICATORY',
    TMJ_01: ['NONE'],
    TMJ_02: 'NO_CONCERN',
    TMJ_03: ['NONE'],
    TMJ_04: 'NO',
    TMJ_05: 'NO_CURRENT_FIXED_LOCK',
  }),
  buildFixture('턱관절 통증 주호소 (TMJ, 안정형 기계적 표현형/무통 클릭)', {
    ID_01: '클릭예시',
    ID_03: 'male',
    BIRTH_01: '19850615',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'chronic_3m_plus',
    VISIT_04_SYMPTOM_IMPACT: 'mild',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'head_face_jaw',
    PAIN_02: ['aching'],
    PAIN_04: 'none',
    // 2. painless click / stable mechanical phenotype -- T7 carve-out:
    // protected safety 전부 negative면 phenotype(클릭/뻣뻣함 등)만으로는
    // escalation을 만들지 않는다. 별도 optional phenotype question이
    // coreSpec.ts에 아직 없으므로(Tablet §3 "may collect"), DIFFUSE_OR_MULTIPLE
    // 경로에서 protected negative만으로 CLEAR가 유지되는지로 T7을 검증한다.
    HFJ_00: 'DIFFUSE_OR_MULTIPLE',
    TMJ_01: ['NONE'],
    TMJ_02: 'NO_CONCERN',
    TMJ_03: ['NONE'],
    TMJ_04: 'NO',
    TMJ_05: 'NO_CURRENT_FIXED_LOCK',
  }),
  buildFixture('턱관절 통증 주호소 (TMJ, 현재 고정된 잠김)', {
    ID_01: '잠김예시',
    ID_03: 'female',
    BIRTH_01: '19921111',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'moderate',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'head_face_jaw',
    PAIN_02: ['movement_related'],
    PAIN_04: 'none',
    // 3. current lock -- TMJ_05 concrete positive -> REVIEW + trauma_or_dislocation_assessment_required.
    HFJ_00: 'JAW_TMJ_MASTICATORY',
    TMJ_01: ['NONE'],
    TMJ_02: 'NO_CONCERN',
    TMJ_03: ['NONE'],
    TMJ_04: 'NO',
    TMJ_05: 'CURRENTLY_LOCKED_AND_CANNOT_OPEN_OR_CLOSE_NORMALLY',
  }),
  buildFixture('턱관절 통증 주호소 (TMJ, 외상 후 교합 변화)', {
    ID_01: '교합변화예시',
    ID_03: 'male',
    BIRTH_01: '19970304',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'severe',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'head_face_jaw',
    PAIN_02: ['sharp'],
    PAIN_04: 'none',
    // 4. trauma + bite change -- TMJ_01 review-only concrete -> REVIEW + trauma, no auto urgent (T3).
    HFJ_00: 'JAW_TMJ_MASTICATORY',
    TMJ_01: ['TRAUMA_WITH_NEW_BITE_CHANGE_OR_MARKED_FUNCTION_LOSS'],
    TMJ_02: 'NO_CONCERN',
    TMJ_03: ['NONE'],
    TMJ_04: 'NO',
    TMJ_05: 'NO_CURRENT_FIXED_LOCK',
  }),
  buildFixture('턱관절 통증 주호소 (TMJ, 턱 고정 비정상 위치 응급)', {
    ID_01: '턱응급예시',
    ID_03: 'female',
    BIRTH_01: '19881010',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'severe',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'head_face_jaw',
    PAIN_02: ['sharp'],
    PAIN_04: 'none',
    // 5. jaw stuck open -- TMJ_01 standalone urgent concrete (T3).
    HFJ_00: 'JAW_TMJ_MASTICATORY',
    TMJ_01: ['JAW_CURRENTLY_STUCK_OPEN_OR_ABNORMAL_POSITION'],
    TMJ_02: 'NO_CONCERN',
    TMJ_03: ['NONE'],
    TMJ_04: 'NO',
    TMJ_05: 'NO_CURRENT_FIXED_LOCK',
  }),
  buildFixture('치아·구강 통증 주호소 (TMJ, 국소 치아 감염 의심)', {
    ID_01: '국소감염예시',
    ID_03: 'male',
    BIRTH_01: '19940707',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'moderate',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'head_face_jaw',
    PAIN_02: ['aching'],
    PAIN_04: 'none',
    // 6. localized dental infection -- TMJ_02 review tier -> REVIEW + dental + infection (T4).
    HFJ_00: 'DENTAL_OR_ORAL',
    TMJ_01: ['NONE'],
    TMJ_02: 'LOCALIZED_TOOTH_OR_GUM_PAIN_SWELLING_OR_PUS_TASTE',
    TMJ_03: ['NONE'],
    TMJ_04: 'NO',
    TMJ_05: 'NO_CURRENT_FIXED_LOCK',
  }),
  buildFixture('치아·구강 통증 주호소 (TMJ, 확산성 치과 응급)', {
    ID_01: '확산응급예시',
    ID_03: 'female',
    BIRTH_01: '19801220',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'severe',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'head_face_jaw',
    PAIN_02: ['sharp'],
    PAIN_04: 'none',
    // 7. spreading dental/oral emergency -- TMJ_02 urgent concrete -> URGENT + infection (T4).
    HFJ_00: 'DENTAL_OR_ORAL',
    TMJ_01: ['NONE'],
    TMJ_02: 'LARGE_OR_SPREADING_SWELLING_OR_SEVERE_SYSTEMIC_ILLNESS',
    TMJ_03: ['NONE'],
    TMJ_04: 'NO',
    TMJ_05: 'NO_CURRENT_FIXED_LOCK',
  }),
  buildFixture('얼굴 감각 이상 주호소 (TMJ, 국소 신경학적 변화)', {
    ID_01: '안면감각예시',
    ID_03: 'male',
    BIRTH_01: '19910505',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'moderate',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'head_face_jaw',
    PAIN_02: ['numbness'],
    PAIN_04: 'none',
    // 8. facial numbness / focal neuro change -- TMJ_04 concrete -> REVIEW + neuro + expedited (T6).
    HFJ_00: 'FACIAL_NEURALGIC',
    TMJ_01: ['NONE'],
    TMJ_02: 'NO_CONCERN',
    TMJ_03: ['NONE'],
    TMJ_04: 'NEW_OR_PERSISTENT_FACIAL_NUMBNESS_OR_FOCAL_NEURO_CHANGE',
    TMJ_05: 'NO_CURRENT_FIXED_LOCK',
  }),
  buildFixture('턱관절 통증 주호소 (TMJ, 50세 이상 GCA 의심 패턴)', {
    ID_01: 'GCA예시',
    ID_03: 'female',
    BIRTH_01: '19600615',
    BIRTH_02: 'solar',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'moderate',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'head_face_jaw',
    PAIN_02: ['aching'],
    PAIN_04: 'none',
    // 9. age >= 50 GCA-compatible pattern -- REVIEW + gca + expedited (T5).
    HFJ_00: 'JAW_TMJ_MASTICATORY',
    TMJ_01: ['NONE'],
    TMJ_02: 'NO_CONCERN',
    TMJ_03: ['NEW_JAW_CLAUDICATION_WITH_CHEWING'],
    TMJ_04: 'NO',
    TMJ_05: 'NO_CURRENT_FIXED_LOCK',
  }),
  buildFixture('턱관절 통증 주호소 (TMJ, GCA 의심+시야 증상 응급)', {
    ID_01: 'GCA시야예시',
    ID_03: 'male',
    BIRTH_01: '19550228',
    BIRTH_02: 'solar',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'severe',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'head_face_jaw',
    PAIN_02: ['aching'],
    PAIN_04: 'none',
    // 10. GCA-compatible + visual symptom, age>=50 -- URGENT (T5).
    HFJ_00: 'JAW_TMJ_MASTICATORY',
    TMJ_01: ['NONE'],
    TMJ_02: 'NO_CONCERN',
    TMJ_03: ['NEW_SCALP_OR_TEMPORAL_PAIN_TENDERNESS_PATTERN', 'NEW_TRANSIENT_VISUAL_DISTURBANCE_DIPLOPIA_OR_VISUAL_LOSS'],
    TMJ_04: 'NO',
    TMJ_05: 'NO_CURRENT_FIXED_LOCK',
  }),
  buildFixture('턱관절 통증 주호소 (TMJ, 나이 미상 GCA 의심 패턴)', {
    ID_01: 'GCA나이미상예시',
    ID_03: 'female',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'moderate',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'head_face_jaw',
    PAIN_02: ['aching'],
    PAIN_04: 'none',
    // 11. age unknown GCA-compatible pattern -- age unknown must NOT be treated as negative;
    // fails closed to REVIEW + gca (not URGENT, per CLOSED tmjLogic.ts semantics -- T5).
    // BIRTH_01 intentionally left null/unanswered (age unknown).
    HFJ_00: 'JAW_TMJ_MASTICATORY',
    TMJ_01: ['NONE'],
    TMJ_02: 'NO_CONCERN',
    TMJ_03: ['NEW_JAW_CLAUDICATION_WITH_CHEWING'],
    TMJ_04: 'NO',
    TMJ_05: 'NO_CURRENT_FIXED_LOCK',
  }),
  buildFixture('두통 주호소 (TMJ population, HEADACHE_CRANIAL 제외)', {
    ID_01: '두통제외예시',
    ID_03: 'male',
    BIRTH_01: '19930909',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'moderate',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'head_face_jaw',
    PAIN_02: ['aching'],
    PAIN_04: 'none',
    // 12. HEADACHE_CRANIAL exclusion -- TMJ_01-05 never shown (T2), safety_flags.tmj must stay null.
    HFJ_00: 'HEADACHE_CRANIAL',
  }),
  buildFixture('머리·얼굴·턱 통증 주호소 (TMJ, HFJ 부위 미상 라우팅)', {
    ID_01: '부위미상예시',
    ID_03: 'female',
    BIRTH_01: '19960101',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'mild',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'head_face_jaw',
    PAIN_02: ['aching'],
    PAIN_04: 'none',
    // 13. HFJ_00 UNKNOWN routing -- still exposes TMJ protected safety (T1/T2), CLEAR when negative.
    HFJ_00: 'UNKNOWN',
    TMJ_01: ['NONE'],
    TMJ_02: 'NO_CONCERN',
    TMJ_03: ['NONE'],
    TMJ_04: 'NO',
    TMJ_05: 'NO_CURRENT_FIXED_LOCK',
  }),
  buildFixture('턱관절 통증 주호소 (TMJ, malformed 응답 회귀)', {
    ID_01: 'malformed예시',
    ID_03: 'male',
    BIRTH_01: '19890808',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'moderate',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'head_face_jaw',
    PAIN_02: ['aching'],
    PAIN_04: 'none',
    // 14. malformed TMJ answers -- TMJ_01 mixes NONE with an out-of-allowlist
    // value; tmjAdapter.ts's asProtectedMulti() must reject this to
    // undefined, which fails closed to REVIEW_REQUIRED (never CLEAR).
    HFJ_00: 'JAW_TMJ_MASTICATORY',
    TMJ_01: ['NONE', 'BOGUS_VALUE'],
    TMJ_02: 'NO_CONCERN',
    TMJ_03: ['NONE'],
    TMJ_04: 'NO',
    TMJ_05: 'NO_CURRENT_FIXED_LOCK',
  }),

  // HIP_V1: shares `low_back_pelvis` population with LBP by design (H1/H7).
  // HIP_GROIN_DOMINANT, all-clear protected answers -> hip_safety_status
  // CLEAR. LBP_* left unanswered since HIP_00 != LOW_BACK_DOMINANT would
  // still leave LBP questions visible per H7 (FROZEN LBP stays unconditional
  // for the whole low_back_pelvis population) -- this fixture only exercises
  // the HIP-clear branch, LBP coexistence is its own fixture below.
  buildFixture('고관절 통증 주호소 (HIP, 안전 확인 완료)', {
    ID_01: '한지민',
    ID_03: 'female',
    BIRTH_01: '19910203',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: '1_3m',
    VISIT_04_SYMPTOM_IMPACT: 'mild',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'low_back_pelvis',
    PAIN_02: ['aching'],
    PAIN_04: 'none',
    LBP_01: 'BACK_ONLY',
    LBP_02: ['NONE'],
    LBP_03: 'NONE',
    LBP_04: ['NONE'],
    LBP_05: ['NONE'],
    LBP_06: 'NO',
    LBP_07: 'NO',
    LBP_08: 'NO',
    LBP_10: 'NO',
    LBP_11: ['NONE'],
    LBP_12: 8,
    LBP_13: 'NO',
    LBP_14: 'NONE',
    HIP_00: 'HIP_GROIN_DOMINANT',
    HIP_01: 'NO',
    HIP_02: ['NONE'],
    HIP_04: ['NONE'],
    HIP_05: 'NO_CONCERN',
    HIP_06: 'NO',
  }),

  // H8 fail-closed: HIP_01 UNKNOWN alone (all else clear) is not a valid
  // negative -> hip_safety_status REVIEW_REQUIRED (never CLEAR).
  buildFixture('고관절 통증 주호소 (HIP, 최근 외상 여부 미상)', {
    ID_01: '오지훈',
    ID_03: 'male',
    BIRTH_01: '19880110',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'moderate',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'low_back_pelvis',
    PAIN_02: ['aching'],
    PAIN_04: 'none',
    LBP_01: 'BACK_ONLY',
    LBP_02: ['NONE'],
    LBP_03: 'NONE',
    LBP_04: ['NONE'],
    LBP_05: ['NONE'],
    LBP_06: 'NO',
    LBP_07: 'NO',
    LBP_08: 'NO',
    LBP_10: 'NO',
    LBP_11: ['NONE'],
    LBP_12: 8,
    LBP_13: 'NO',
    LBP_14: 'NONE',
    HIP_00: 'BUTTOCK_PELVIS_DOMINANT',
    HIP_01: 'UNKNOWN',
    HIP_02: ['NONE'],
    HIP_04: ['NONE'],
    HIP_05: 'NO_CONCERN',
    HIP_06: 'NO',
  }),

  // H2 limb-threatening always-urgent: GROSS_DEFORMITY -> URGENT_REVIEW.
  buildFixture('고관절 통증 주호소 (HIP, 관절 변형 응급)', {
    ID_01: '최우진',
    ID_03: 'male',
    BIRTH_01: '19650720',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'severe',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'low_back_pelvis',
    PAIN_02: ['sharp'],
    PAIN_04: 'none',
    LBP_01: 'BACK_ONLY',
    LBP_02: ['NONE'],
    LBP_03: 'NONE',
    LBP_04: ['NONE'],
    LBP_05: ['NONE'],
    LBP_06: 'NO',
    LBP_07: 'NO',
    LBP_08: 'NO',
    LBP_10: 'NO',
    LBP_11: ['NONE'],
    LBP_12: 8,
    LBP_13: 'NO',
    LBP_14: 'NONE',
    HIP_00: 'HIP_GROIN_DOMINANT',
    HIP_01: 'YES',
    HIP_02: ['GROSS_DEFORMITY_OR_JOINT_STUCK_OUT_OF_POSITION'],
    HIP_03: 'MARKED_WEIGHT_BEARING_OR_WALKING_DIFFICULTY',
    HIP_04: ['NONE'],
    HIP_05: 'NO_CONCERN',
    HIP_06: 'NO',
  }),

  // H2 traumatic major distal neuro deficit + acute trauma -> standalone
  // URGENT_REVIEW (not just review+neuro).
  buildFixture('고관절 통증 주호소 (HIP, 외상 후 다리 신경 손상 응급)', {
    ID_01: '신동엽',
    ID_03: 'male',
    BIRTH_01: '19780914',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'severe',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'low_back_pelvis',
    PAIN_02: ['aching'],
    PAIN_04: 'lower_limb',
    LBP_01: 'BACK_ONLY',
    LBP_02: ['NONE'],
    LBP_03: 'NONE',
    LBP_04: ['NONE'],
    LBP_05: ['NONE'],
    LBP_06: 'NO',
    LBP_07: 'NO',
    LBP_08: 'NO',
    LBP_10: 'NO',
    LBP_11: ['NONE'],
    LBP_12: 8,
    LBP_13: 'NO',
    LBP_14: 'NONE',
    HIP_00: 'HIP_GROIN_DOMINANT',
    HIP_01: 'YES',
    HIP_02: ['NEW_MAJOR_DISTAL_NUMBNESS_OR_WEAKNESS_AFTER_TRAUMA'],
    HIP_03: 'NO_MARKED_WALKING_DIFFICULTY',
    HIP_04: ['NONE'],
    HIP_05: 'NO_CONCERN',
    HIP_06: 'NO',
  }),

  // Same major neuro finding WITHOUT trauma -> REVIEW_REQUIRED + neuro +
  // expedited (not urgent) -- H2's trauma-neuro urgent branch requires
  // concrete trauma; non-traumatic stays review-tier.
  buildFixture('고관절 통증 주호소 (HIP, 외상 없는 다리 신경 증상)', {
    ID_01: '윤서아',
    ID_03: 'female',
    BIRTH_01: '19921125',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: '1_3m',
    VISIT_04_SYMPTOM_IMPACT: 'moderate',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'low_back_pelvis',
    PAIN_02: ['aching'],
    PAIN_04: 'lower_limb',
    LBP_01: 'BACK_ONLY',
    LBP_02: ['NONE'],
    LBP_03: 'NONE',
    LBP_04: ['NONE'],
    LBP_05: ['NONE'],
    LBP_06: 'NO',
    LBP_07: 'NO',
    LBP_08: 'NO',
    LBP_10: 'NO',
    LBP_11: ['NONE'],
    LBP_12: 8,
    LBP_13: 'NO',
    LBP_14: 'NONE',
    HIP_00: 'SIMILAR_OR_MULTIPLE',
    HIP_01: 'NO',
    HIP_02: ['NEW_MAJOR_DISTAL_NUMBNESS_OR_WEAKNESS_AFTER_TRAUMA'],
    HIP_04: ['NONE'],
    HIP_05: 'NO_CONCERN',
    HIP_06: 'NO',
  }),

  // H3 post-traumatic marked weight-bearing/walking difficulty -> REVIEW +
  // fracture_imaging_consider + expedited. HIP_03A prior "told normal" X-ray
  // is context only and must NOT lower this to CLEAR or suppress imaging
  // consideration (H4).
  buildFixture('고관절 통증 주호소 (HIP, 외상 후 보행 곤란 + 이전 X-ray 정상)', {
    ID_01: '장미란',
    ID_03: 'female',
    BIRTH_01: '19700815',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'severe',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'low_back_pelvis',
    PAIN_02: ['aching', 'movement_related'],
    PAIN_04: 'none',
    LBP_01: 'BACK_ONLY',
    LBP_02: ['NONE'],
    LBP_03: 'NONE',
    LBP_04: ['NONE'],
    LBP_05: ['NONE'],
    LBP_06: 'NO',
    LBP_07: 'NO',
    LBP_08: 'NO',
    LBP_10: 'NO',
    LBP_11: ['NONE'],
    LBP_12: 8,
    LBP_13: 'NO',
    LBP_14: 'NONE',
    HIP_00: 'HIP_GROIN_DOMINANT',
    HIP_01: 'YES',
    HIP_02: ['NONE'],
    HIP_03: 'MARKED_WEIGHT_BEARING_OR_WALKING_DIFFICULTY',
    HIP_03A: 'DONE_TOLD_NORMAL',
    HIP_04: ['NONE'],
    HIP_05: 'NO_CONCERN',
    HIP_06: 'NO',
  }),

  // H5 femoral-neck stress-fracture compatible pattern (all three approved
  // elements) -> REVIEW + stress_fracture_assessment_required +
  // fracture_imaging_consider + loading_exercise_lock.
  buildFixture('고관절 통증 주호소 (HIP, 피로골절 의심 패턴)', {
    ID_01: '백승호',
    ID_03: 'male',
    BIRTH_01: '19990512',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: '1_3m',
    VISIT_04_SYMPTOM_IMPACT: 'moderate',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'low_back_pelvis',
    PAIN_02: ['aching', 'movement_related'],
    PAIN_04: 'none',
    LBP_01: 'BACK_ONLY',
    LBP_02: ['NONE'],
    LBP_03: 'NONE',
    LBP_04: ['NONE'],
    LBP_05: ['NONE'],
    LBP_06: 'NO',
    LBP_07: 'NO',
    LBP_08: 'NO',
    LBP_10: 'NO',
    LBP_11: ['NONE'],
    LBP_12: 8,
    LBP_13: 'NO',
    LBP_14: 'NONE',
    HIP_00: 'HIP_GROIN_DOMINANT',
    HIP_01: 'NO',
    HIP_02: ['NONE'],
    HIP_04: [
      'ATRAUMATIC_OR_INSIDIOUS_DEEP_HIP_OR_GROIN_PAIN',
      'RECENT_REPETITIVE_LOAD_RUNNING_JUMPING_MARCH_OR_LOAD_INCREASE',
      'PROGRESSIVE_WEIGHT_BEARING_PAIN_OR_WORSENING_WALKING_TOLERANCE',
    ],
    HIP_05: 'NO_CONCERN',
    HIP_06: 'NO',
  }),

  // H5 partial pattern (only one compatible element) must NOT auto-diagnose
  // a stress fracture -- stress_fracture_assessment_required stays false,
  // though it remains a protected non-negative history (still REVIEW).
  buildFixture('고관절 통증 주호소 (HIP, 부분 피로골절 패턴/자동 진단 아님)', {
    ID_01: '남궁민',
    ID_03: 'male',
    BIRTH_01: '19960228',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: '1_3m',
    VISIT_04_SYMPTOM_IMPACT: 'mild',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'low_back_pelvis',
    PAIN_02: ['aching'],
    PAIN_04: 'none',
    LBP_01: 'BACK_ONLY',
    LBP_02: ['NONE'],
    LBP_03: 'NONE',
    LBP_04: ['NONE'],
    LBP_05: ['NONE'],
    LBP_06: 'NO',
    LBP_07: 'NO',
    LBP_08: 'NO',
    LBP_10: 'NO',
    LBP_11: ['NONE'],
    LBP_12: 8,
    LBP_13: 'NO',
    LBP_14: 'NONE',
    HIP_00: 'HIP_GROIN_DOMINANT',
    HIP_01: 'NO',
    HIP_02: ['NONE'],
    HIP_04: ['ATRAUMATIC_OR_INSIDIOUS_DEEP_HIP_OR_GROIN_PAIN'],
    HIP_05: 'NO_CONCERN',
    HIP_06: 'NO',
  }),

  // H6 localized/stable infection concern -> REVIEW + infection_assessment.
  buildFixture('고관절 통증 주호소 (HIP, 국소 감염 의심)', {
    ID_01: '구자철',
    ID_03: 'male',
    BIRTH_01: '19830630',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'moderate',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'low_back_pelvis',
    PAIN_02: ['burning'],
    PAIN_04: 'none',
    LBP_01: 'BACK_ONLY',
    LBP_02: ['NONE'],
    LBP_03: 'NONE',
    LBP_04: ['NONE'],
    LBP_05: ['NONE'],
    LBP_06: 'NO',
    LBP_07: 'NO',
    LBP_08: 'NO',
    LBP_10: 'NO',
    LBP_11: ['NONE'],
    LBP_12: 8,
    LBP_13: 'NO',
    LBP_14: 'NONE',
    HIP_00: 'HIP_GROIN_DOMINANT',
    HIP_01: 'NO',
    HIP_02: ['NONE'],
    HIP_04: ['NONE'],
    HIP_05: 'LOCALIZED_STABLE_CONCERN',
    HIP_06: 'NO',
  }),

  // H6 systemic illness OR rapidly worsening pain -> URGENT_REVIEW +
  // infection_assessment_required. Opaque OR enum -- fever absence is never
  // recorded here and must not be treated as a rule-out.
  buildFixture('고관절 통증 주호소 (HIP, 전신 증상 동반 감염 응급)', {
    ID_01: '민경아',
    ID_03: 'female',
    BIRTH_01: '19770404',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'severe',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'low_back_pelvis',
    PAIN_02: ['burning'],
    PAIN_04: 'none',
    LBP_01: 'BACK_ONLY',
    LBP_02: ['NONE'],
    LBP_03: 'NONE',
    LBP_04: ['NONE'],
    LBP_05: ['NONE'],
    LBP_06: 'NO',
    LBP_07: 'NO',
    LBP_08: 'NO',
    LBP_10: 'NO',
    LBP_11: ['NONE'],
    LBP_12: 8,
    LBP_13: 'NO',
    LBP_14: 'NONE',
    HIP_00: 'BUTTOCK_PELVIS_DOMINANT',
    HIP_01: 'NO',
    HIP_02: ['NONE'],
    HIP_04: ['NONE'],
    HIP_05: 'SYSTEMIC_OR_RAPIDLY_WORSENING',
    HIP_06: 'NO',
  }),

  // H2 non-traumatic progressive distal numbness/weakness (HIP_06) ->
  // REVIEW + neuro_assessment_required + expedited_referral_consider.
  buildFixture('고관절 통증 주호소 (HIP, 비외상성 진행성 신경 증상)', {
    ID_01: '고아라',
    ID_03: 'female',
    BIRTH_01: '19890917',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: '3m_1y',
    VISIT_04_SYMPTOM_IMPACT: 'moderate',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'low_back_pelvis',
    PAIN_02: ['aching'],
    PAIN_04: 'lower_limb',
    LBP_01: 'BACK_ONLY',
    LBP_02: ['NONE'],
    LBP_03: 'NONE',
    LBP_04: ['NONE'],
    LBP_05: ['NONE'],
    LBP_06: 'NO',
    LBP_07: 'NO',
    LBP_08: 'NO',
    LBP_10: 'NO',
    LBP_11: ['NONE'],
    LBP_12: 8,
    LBP_13: 'NO',
    LBP_14: 'NONE',
    HIP_00: 'SIMILAR_OR_MULTIPLE',
    HIP_01: 'NO',
    HIP_02: ['NONE'],
    HIP_04: ['NONE'],
    HIP_05: 'NO_CONCERN',
    HIP_06: 'NEW_OR_PROGRESSIVE_DISTAL_NUMBNESS_OR_WEAKNESS',
  }),

  // H1/H7 coexistence: HIP_GROIN_DOMINANT patient still gets the full FROZEN
  // LBP protected safety computed unconditionally (LBP_04 CES screen concrete
  // review-tier value here) alongside a HIP-tier positive (full stress
  // pattern) -- both `safety_flags.lbp` and `safety_flags.hip` must be
  // non-null and neither may suppress the other. DoctorView must render both
  // LbpSafetyPanel and HipSafetyPanel for this fixture.
  buildFixture('고관절 통증 주호소 (HIP+LBP 동시 노출)', {
    ID_01: '표창원',
    ID_03: 'male',
    BIRTH_01: '19820525',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: '3m_1y',
    VISIT_04_SYMPTOM_IMPACT: 'moderate',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'low_back_pelvis',
    PAIN_02: ['aching', 'movement_related'],
    PAIN_04: 'lower_limb',
    LBP_01: 'BUTTOCK',
    LBP_02: ['NUMBNESS'],
    LBP_03: 'BILATERAL',
    LBP_04: ['NONE'],
    LBP_05: ['NONE'],
    LBP_06: 'NO',
    LBP_07: 'YES',
    LBP_08: 'NO',
    LBP_10: 'NO',
    LBP_11: ['NONE'],
    LBP_12: 6,
    LBP_13: 'SOMEWHAT',
    LBP_14: 'SOME',
    HIP_00: 'HIP_GROIN_DOMINANT',
    HIP_01: 'NO',
    HIP_02: ['NONE'],
    HIP_04: [
      'ATRAUMATIC_OR_INSIDIOUS_DEEP_HIP_OR_GROIN_PAIN',
      'RECENT_REPETITIVE_LOAD_RUNNING_JUMPING_MARCH_OR_LOAD_INCREASE',
      'PROGRESSIVE_WEIGHT_BEARING_PAIN_OR_WORSENING_WALKING_TOLERANCE',
    ],
    HIP_05: 'NO_CONCERN',
    HIP_06: 'NO',
  }),

  // Core general_red (SAFETY_01) coexistence: `core_safety_already_urgent`
  // forces hip_safety_status to URGENT_REVIEW even though every HIP-specific
  // answer here is otherwise clear -- mirrors every other module's "core
  // urgent dominates" CLOSED behavior (hip.spec.mjs).
  buildFixture('고관절 통증 주호소 (HIP, Core 전신 응급 동시)', {
    ID_01: '전지현',
    ID_03: 'female',
    BIRTH_01: '19810427',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'severe',
    SECONDARY_01: ['none'],
    SAFETY_01: ['sudden_severe_pain'],
    PAIN_01: 'low_back_pelvis',
    PAIN_02: ['aching'],
    PAIN_04: 'none',
    LBP_01: 'BACK_ONLY',
    LBP_02: ['NONE'],
    LBP_03: 'NONE',
    LBP_04: ['NONE'],
    LBP_05: ['NONE'],
    LBP_06: 'NO',
    LBP_07: 'NO',
    LBP_08: 'NO',
    LBP_10: 'NO',
    LBP_11: ['NONE'],
    LBP_12: 8,
    LBP_13: 'NO',
    LBP_14: 'NONE',
    HIP_00: 'HIP_GROIN_DOMINANT',
    HIP_01: 'NO',
    HIP_02: ['NONE'],
    HIP_04: ['NONE'],
    HIP_05: 'NO_CONCERN',
    HIP_06: 'NO',
  }),

  // H1 routing boundary: LOW_BACK_DOMINANT never exposes HIP-specific
  // protected questions (HIP_01-06 stay unanswered/hidden) -- HIP_00 itself
  // never creates a safety tier. `safety_flags.hip` must stay null and
  // HipSafetyPanel must not render, while FROZEN LBP stays fully active and
  // unaffected (same population, LBP_* answered normally).
  buildFixture('허리 통증 주호소 (HIP population, LOW_BACK_DOMINANT 제외)', {
    ID_01: '유재석',
    ID_03: 'male',
    BIRTH_01: '19720819',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'over_1y',
    VISIT_04_SYMPTOM_IMPACT: 'mild',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'low_back_pelvis',
    PAIN_02: ['aching'],
    PAIN_04: 'none',
    LBP_01: 'BACK_ONLY',
    LBP_02: ['NONE'],
    LBP_03: 'NONE',
    LBP_04: ['NONE'],
    LBP_05: ['NONE'],
    LBP_06: 'NO',
    LBP_07: 'NO',
    LBP_08: 'NO',
    LBP_10: 'NO',
    LBP_11: ['NONE'],
    LBP_12: 8,
    LBP_13: 'NO',
    LBP_14: 'NONE',
    HIP_00: 'LOW_BACK_DOMINANT',
  }),

  // H8 fail-closed runtime safety: HIP_02 mixes NONE with an out-of-allowlist
  // value; hipAdapter.ts's asProtectedMulti() must reject this to undefined,
  // which fails closed to REVIEW_REQUIRED (never CLEAR) -- TypeScript union
  // casts alone cannot be trusted for a runtime-submitted payload.
  buildFixture('고관절 통증 주호소 (HIP, malformed 응답 회귀)', {
    ID_01: 'malformed예시',
    ID_03: 'male',
    BIRTH_01: '19900101',
    VISIT_01: 'symptom',
    VISIT_02_SYMPTOM_MAIN: 'pain',
    VISIT_03_SYMPTOM_DURATION: 'within_1w',
    VISIT_04_SYMPTOM_IMPACT: 'moderate',
    SECONDARY_01: ['none'],
    SAFETY_01: ['none'],
    PAIN_01: 'low_back_pelvis',
    PAIN_02: ['aching'],
    PAIN_04: 'none',
    LBP_01: 'BACK_ONLY',
    LBP_02: ['NONE'],
    LBP_03: 'NONE',
    LBP_04: ['NONE'],
    LBP_05: ['NONE'],
    LBP_06: 'NO',
    LBP_07: 'NO',
    LBP_08: 'NO',
    LBP_10: 'NO',
    LBP_11: ['NONE'],
    LBP_12: 8,
    LBP_13: 'NO',
    LBP_14: 'NONE',
    HIP_00: 'HIP_GROIN_DOMINANT',
    HIP_01: 'NO',
    HIP_02: ['NONE', 'BOGUS_VALUE'],
    HIP_04: ['NONE'],
    HIP_05: 'NO_CONCERN',
    HIP_06: 'NO',
  }),
]
